- name: "Multiple Shell"
  hosts: all
  tasks:
    - name: "Exec items"
      shell: "{{ item }}"
      with_items:
        - echo "hello"
        - date
        - ls
       register: shell_result
    - debug:
        var: shell_result.stdout_lines